version: '3.1'
services:
  yourls:
    image: yourls
    container_name: yourls
    restart: always
    ports:
      - "8082:80"
    volumes:
      - ./user/plugins:/var/www/html/user/plugins/
    environment:
      YOURLS_DB_HOST: host.docker.internal:3306
      YOURLS_DB_USER: root
      YOURLS_DB_PASS: champl00
      YOURLS_DB_NAME: urls
      YOURLS_DB_TABLE_PREFIX: urls_
      YOURLS_SITE: https://example.com
      YOURLS_USER: example_username
      YOURLS_PASS: example_password
