version: '3.1'
services:
  yourls:
    image: yourls
    container_name: yourls
    restart: always
    ports:
      - "8082:80"
    volumes:
      - ./user:/var/www/html/user/
    environment:
      YOURLS_DB_HOST: host.docker.internal:3306
      YOURLS_DB_USER: root
      YOURLS_DB_PASS: champl00
      YOURLS_DB_NAME: yourls
      YOURLS_DB_TABLE_PREFIX: urls_
      YOURLS_SITE: http://localhost:8082
      YOURLS_USER: admin
      YOURLS_PASS: rights
